server:
  port: 10010
  tomcat:  #修改内置tomcat上传文件大小
    max-http-post-size: -1
spring:
  application:
    name: gateway
  servlet:
    multipart:
      enabled: true
      max-file-size: 500MB
      max-request-size: 1024MB
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
    registry-fetch-interval-seconds: 5
  instance:
    instance-id: ${spring.application.name}:${server.port}
    prefer-ip-address: true  #当你获取host时，返回的不是主机名，而是ip
    ip-address: 127.0.0.1

zuul:
  prefix: /api # 添加路由前缀
  retryable: true
  routes:
    blog-service: /blog/**  #社交微服务
    user-service: /user/**  #用户微服务
    question-service: /question/** #学习微服务
    course-service: /course/** #学习微服务
    study-service: /study/** #学习微服务
    manage-service: /manage/** #学习微服务
  ignored-services:
    - upload-service # 忽略upload-service服务
  add-host-header: true #携带请求本身的head头信息
  sensitive-headers: #匹配禁止使用的头信息，这里设置为null，否则set-cookie无效
ribbon:
  ConnectTimeout: 250 # 连接超时时间(ms)
  ReadTimeout: 2000 # 通信超时时间(ms)
  OkToRetryOnAllOperations: true # 是否对所有操作重试
  MaxAutoRetriesNextServer: 1 # 同一服务不同实例的重试次数
  MaxAutoRetries: 1 # 同一实例的重试次数
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMillisecond: 10000 # 熔断超时时长：10000ms
