server:
  port: 8082
spring:
  application:
    name: course-service
  servlet:
    multipart:
      enabled: true
      max-file-size: 500MB
      max-request-size: 1024MB
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/study?characterEncoding=UTF-8&useSSL=false
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
    hikari:
      maximum-pool-size: 20
      minimum-idle: 10
      #配置rabbitMq 服务器
  rabbitmq:
    host: 192.168.183.130
    port: 5672
    username: guest
    password: guest
    #配置自动建表：updata:没有表新建，有表更新操作,控制台显示建表语句
    jpa:
      hibernate:
        ddl-auto: update
      show-sql: true
logging:
  level:
    com.tao.course.mapper: debug



eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
    registry-fetch-interval-seconds: 5
  instance:
    instance-id: ${spring.application.name}:${server.port}
    prefer-ip-address: true  #当你获取host时，返回的不是主机名，而是ip
    ip-address: 127.0.0.1
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 10

ribbon:
  ConnectTimeout: 250 # 连接超时时间(ms)
  ReadTimeout: 2000 # 通信超时时间(ms)
  OkToRetryOnAllOperations: true # 是否对所有操作重试
  MaxAutoRetriesNextServer: 1 # 同一服务不同实例的重试次数
  MaxAutoRetries: 1 # 同一实例的重试次数
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMillisecond: 10000 # 熔断超时时长：10000ms
